databases:
  - name: mindwall-db
    databaseName: mindwalldb
    user: mindwalluser

services:
  - type: web
    name: Mindwall-backend
    env: python
    region: ohio
    buildCommand: "./build.sh"
    startCommand: "gunicorn --workers=2 backend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ORIGINS
        value: "https://mindwall-frontend.onrender.com"
      - key: PYTHON_VERSION
        value: 3.11.0
      - fromDatabase:
          name: mindwall-db
          property: connectionString
        key: DATABASE_URL
